name: Build Docker Image & Compare with Scout

on:
  push:

env:
  AWS_REGION: 'ap-northeast-1'
  AWS_ROLE_ARN: 'arn:aws:iam::175142243308:role/tadashi-docker-scout-demo-role'
  REGISTRY: '175142243308.dkr.ecr.ap-northeast-1.amazonaws.com'
  REPOSITORY: 'tadashi/docker-scout-demo'
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_SCOUT_HUB_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_SCOUT_HUB_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_SCOUT_REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_SCOUT_REGISTRY_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - run: |
          docker build -t $REPOSITORY:$IMAGE_TAG .
      - uses: docker/scout-action@v1
        with:
            command: compare
            image: '${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}'
            to: production
            ignore-unchanged: true
            only-severities: critical,high
            write-comment: true
            organization: tadashinemoto567
