name: Build Docker Image & Compare with Scout

on:
  push:

env:
  DOCKERHUB_REPOSITORY: 'tadashinemoto567/docker-scout-demo'
  IMAGE_TAG: ${{ github.sha }}

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ env.DOCKERHUB_REPOSITORY }}
      - uses: docker/scout-action@v1
        with:
            command: compare
            image: ${{ env.DOCKERHUB_REPOSITORY }}
            to: production
            ignore-unchanged: true
            only-severities: critical,high
            write-comment: true
            organization: tadashinemoto567
