name: Build Docker Image & Compare with Scout

on:
  pull_request:

env:
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_SCOUT_HUB_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_SCOUT_HUB_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
  DOCKERHUB_REPOSITORY: 'tadashinemoto567/docker-scout-demo'

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          provenance: true
          tags: ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
      - id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          to-env: production
          organization: tadashinemoto567
