name: Build Docker Image & Compare with Scout

on:
  push:

env:
  REPOSITORY: 'tadashi/docker-scout-demo'
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_SCOUT_HUB_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_SCOUT_HUB_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: ${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
      - uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          organization: tadashinemoto567
